### ISSUE TITLE
Consider using `@digitalbazaar/ezcap@4`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-exchanger#20]
https://github.com/digitalbazaar/ezcap/blob/main/CHANGELOG.md#400---2022-10-25

What would the impacts be here, what type of release?

**Comment by dlongley** [comment]
Ideally, we replace whatever is using this package with using an exchanger service (which runs on `bedrock-vc-delivery`) and archive this whole repo.

**Comment by dlongley** [comment]
That being said -- `ezcap@4` uses dependencies that turn on safe mode for canonizing by default, which shouldn't have an effect here since all payloads should already be properly defined (safe mode throws errors for payloads with undefined information).
